[project]
name = "solax"
version = "0.1.0"
description = "Solax inverter API wrapper"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.5.4",
    "importlib-metadata>=3.6 ; python_full_version < '3.10'",
    "typing-extensions>=4.1.0 ; python_full_version < '3.11'",
    "voluptuous>=0.11.5",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
    "coverage>=7.10.7",
    "flake8>=7.3.0",
    "isort>=6.1.0",
    "mypy>=1.19.0",
    "pylint>=3.3.9",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.0.0",
    "pytest-httpserver>=1.1.3",
]
